import { uid } from "@/lib/utils";
import type { ModelState } from "@/lib/model/types";

export function seedModel(): ModelState {
  return {
    area: "Nederland – voorbeeldgebied",
    asOf: "2026-12-31",
    priceLevel: "september 2026",
    targetCoverage: 0.95,
    activeScenarioId: 2,
    scenarios: [
      { id: 1, name: "Zonder basisinkomen", adult: 0, child: 0 },
      { id: 2, name: "Laag", adult: 800, child: 0 },
      { id: 3, name: "Midden", adult: 1000, child: 150 },
      { id: 4, name: "Hoog", adult: 1200, child: 250 },
      { id: 5, name: "Ruim", adult: 1400, child: 350 },
    ],
    housing: [
      {
        id: uid(),
        name: "Alleenstaande · Stad Centrum",
        demand: 1000,
        available: 850,
        quality: 800,
        affordable: 760,
      },
      {
        id: uid(),
        name: "Paar zonder kinderen · Stad Centrum",
        demand: 600,
        available: 550,
        quality: 520,
        affordable: 500,
      },
      {
        id: uid(),
        name: "Gezin met kinderen · Stad Noord",
        demand: 750,
        available: 680,
        quality: 650,
        affordable: 610,
      },
      {
        id: uid(),
        name: "Alleenstaande oudere · Regio Oost",
        demand: 400,
        available: 300,
        quality: 280,
        affordable: 240,
      },
      {
        id: uid(),
        name: "Huishouden met beperking · Regio Oost",
        demand: 180,
        available: 110,
        quality: 95,
        affordable: 80,
      },
      {
        id: uid(),
        name: "Starter · Regio Zuid",
        demand: 500,
        available: 390,
        quality: 370,
        affordable: 320,
      },
    ],
    households: [
      {
        id: uid(),
        name: "Alleenstaande werkend",
        adults: 1,
        children: 0,
        weight: 800,
        otherIncome: 1650,
        housingEnergy: 850,
        otherMin: 950,
        adequateHome: true,
      },
      {
        id: uid(),
        name: "Alleenstaande zonder werk",
        adults: 1,
        children: 0,
        weight: 600,
        otherIncome: 950,
        housingEnergy: 760,
        otherMin: 950,
        adequateHome: true,
      },
      {
        id: uid(),
        name: "Paar zonder kinderen",
        adults: 2,
        children: 0,
        weight: 500,
        otherIncome: 2100,
        housingEnergy: 950,
        otherMin: 1400,
        adequateHome: true,
      },
      {
        id: uid(),
        name: "Gezin met twee kinderen",
        adults: 2,
        children: 2,
        weight: 650,
        otherIncome: 2400,
        housingEnergy: 1150,
        otherMin: 1900,
        adequateHome: true,
      },
      {
        id: uid(),
        name: "Alleenstaande oudere",
        adults: 1,
        children: 0,
        weight: 350,
        otherIncome: 1450,
        housingEnergy: 780,
        otherMin: 1000,
        adequateHome: true,
      },
      {
        id: uid(),
        name: "Beperking en hoge zorgkosten",
        adults: 1,
        children: 0,
        weight: 120,
        otherIncome: 1200,
        housingEnergy: 850,
        otherMin: 1250,
        adequateHome: true,
      },
      {
        id: uid(),
        name: "Starter zonder adequate woning",
        adults: 1,
        children: 0,
        weight: 400,
        otherIncome: 1500,
        housingEnergy: 900,
        otherMin: 950,
        adequateHome: false,
      },
    ],
    finance: {
      adultRecipients: 10_000,
      childRecipients: 2_000,
      adminCost: 5_000_000,
      extraTax: 25_000_000,
      savings: 15_000_000,
    },
  };
}
